dist: trusty
os:
  - linux

language: node_js

node_js:
  - '14'

cache:
  directories:
    - ~/.npm
    - node_modules
  npm: true

addons:
  sonarcloud:
    organization: ankeshgautam

install:
  - npm install

script:
  - npm run build
  - sonar-scanner